# Generated by Django 5.2.1 on 2025-06-10 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0011_final_fix"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("event", "seat")},
        ),
    ]
