# Generated by Django 5.2.11 on 2026-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_orderdetails_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='ticket_UUID',
            new_name='ticket_uuid',
        ),
        migrations.AddField(
            model_name='order',
            name='tickets_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets_pdfs'),
        ),
    ]
