# Generated by Django 5.2.11 on 2026-03-04 13:07

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_remove_event_event_date_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='pesel',
            field=encrypted_model_fields.fields.EncryptedCharField(default=556, verbose_name=models.CharField(blank=True, null=True)),
            preserve_default=False,
        ),
    ]
