# Generated by Django 5.2.11 on 2026-03-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0020_event_image_alter_event_start_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="tickets.order",
            ),
        ),
    ]
